name: Welcome First Issue

on:
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome New Contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Hello and welcome to the **GitHub Actions Demo** repository maintained by **Hirdepal Singh**!

            Thank you for opening your first issue here! 🎉  
            We appreciate your contribution and are excited to collaborate with you.

            If you have any questions or need help, feel free to ask.  
            Happy contributing! 🚀
          pr-message: ""
